### PR TITLE
feat: add SnifferEggBugFix

### PR DESCRIPTION
**Pull request by Yushu2606**
## Checklist before merging

Thank you for your contribution to the repository. 
Before submitting this PR, please make sure:

- [ ] Your code builds clean without any errors or warnings
- [ ] Your code follows [LeviLamina C++ Style Guide](https://github.com/LiteLDev/LeviLamina/wiki/CPP-Style-Guide)
- [ ] You have tested all functions
- [ ] You have not used code without license
- [ ] You have added statement for third-party code

### CODE REVIEW

**Comment by OEOTYAN** [comment]
这是什么bug

**Comment by OEOTYAN** [comment]
emmmmmmm 能不能留个bugs.mojang.com的链接或者描述一下这bug怎么回事

**Comment by Yushu2606** [comment]
https://bugs.mojang.com/browse/MCPE-172773
https://bugs.mojang.com/browse/MCPE-174063
嗅探兽蛋被移除后，对应坐标的计划刻不会随之移除的问题

**Comment by Yushu2606** [comment]
> emmmmmmm 能不能留个bugs.mojang.com的链接或者描述一下这bug怎么回事

抱歉疏忽了

**Pull request merged**
